"""empty message

Revision ID: 3a956af13657
Revises: 
Create Date: 2021-12-06 09:34:31.699943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a956af13657'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'image_file',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cart', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart_item', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'gender',
               existing_type=sa.TEXT(length=10),
               nullable=False)
    op.alter_column('user_product', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_product', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_product', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_product', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'gender',
               existing_type=sa.TEXT(length=10),
               nullable=True)
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart_item', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart', 'image_file',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
